### PR TITLE
Convert codebase to TypeScript

### LINKED ISSUE #85: TypeScript declarations
Would be nice to have TS declarations exposed.

### PR DESCRIPTION
**Pull request by PaulLeCam**
Sorry for the large diff, there are a bunch of things I needed to change for the TS compiler to stop complaining.

I moved the `connectLegacyService.js` file to the `legacy` folder because it didn't seem to be exposed in the lib or used in the iframe, but I can convert it to TS as well in case we need it?

One thing I couldn't understand is how some methods are bound here: https://github.com/3box/3id-connect/blob/typescript/src/threeIdConnect.ts#L135-L136
The TS compiler also complains about this method: https://github.com/3box/3id-connect/blob/typescript/example/app.ts#L42, I'm still going through the logic to make sure these flows work.

Closes https://github.com/3box/3id-connect/issues/85

### CODE REVIEW

**Review by oed — COMMENTED** [review]
lgtm, Zach probably has better input since he knows the codebase

**Comment by zachferland** [comment]
awesome! only had enough time to quickly glance through today

want to merge into dev @ https://github.com/ceramicstudio/3id-connect now?, ceramic version moved there now, shouldnt be any conflicts there, feel free to merge if makes working on it easier

we can remove the connectLegacy service now

> One thing I couldn't understand is how some methods are bound here: https://github.com/3box/3id-connect/blob/typescript/src/threeIdConnect.ts#L135-L136

those methods are called by iframe service, ie iframe is the rpc client in this case, so they will never be called before connect() is called. the _authenticate/_create are not public methods and the authprovider calls are just auth/create link in 3id-blockchain-utils, so those dont make any rpc calls, just return authsecret/linkproof to iframe, not sure if that answers

**Comment by PaulLeCam** [comment]
Thanks!
Sure I'll merge the dev branch into this one, I'm putting this PR on hold for now as we'll need to update the dependencies on Ceramic and IDX anyways but I'll try to get it to a good state once these dependencies are pushed.

**Comment by zachferland** [comment]
Merged here - https://github.com/ceramicstudio/3id-connect/pull/3

3id-connect with ceramic support now entirely here https://github.com/ceramicstudio/3id-connect, while 3id-connect for 3box remains in this repo

**Pull request closed without merging**
